[[customizations.user]]
name = "turt"
password = "turtlinux"
description = "TurtLinux User"
groups = ["wheel"]

[[customizations.files]]
path = "/usr/lib/os-release"
data = '''
NAME="TurtLinux"
PRETTY_NAME="TurtLinux 44"
VERSION="44"
VERSION_ID="44"
ID=turtlinux
ID_LIKE=fedora
HOME_URL="https://turtlinux.ingstudios.dev"
LOGO=turtlinux
'''