FROM quay.io/fedora/fedora-bootc:44

# Default programs
RUN dnf install -y \
        @kde-desktop \
        plasma-workspace-wayland \
        chromium \
        git \
        micro && \
    dnf clean all

# Customize KDE panel
COPY ./assets/panel/start-here-turtlinux.svg /usr/share/icons/hicolor/scalable/apps/start-here-turtlinux.svg
COPY ./assets/panel/content.js /usr/share/plasma/layout-templates/org.kde.plasma.desktop.defaultPanel/contents/layout.js
RUN gtk-update-icon-cache -f /usr/share/icons/hicolor/

RUN bootc container lint