print_info() {
    info os
    info host
    info kernel
    info uptime
    info packages
    info shell
    info de
    info wm
    info terminal
    info cpu
    info gpu
    info memory
    info cols
}

image_backend="w3m"
image_source="/usr/share/pixmaps/turtlinux.png"
image_size="auto"