name: Build TurtLinux
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Build Image using Podman
        run: |
          IMAGE_PATH=$(echo "ghcr.io/${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          podman build -t $IMAGE_PATH:latest .

      - name: Log into GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | podman login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push Image to GHCR
        run: |
          IMAGE_PATH=$(echo "ghcr.io/${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          podman push $IMAGE_PATH:latest